// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm4WAYvSGC4_dIXuuk5ITZSXzvtQvkhTA',
    appId: '1:163516367513:android:d09ac341032bf1cb9cae08',
    messagingSenderId: '163516367513',
    projectId: 'guia-roteiro-vinho',
    storageBucket: 'guia-roteiro-vinho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIzNg-8oijQQoUv7jeRdqvuc9ZGHzTzho',
    appId: '1:163516367513:ios:578a6cbf3427ac449cae08',
    messagingSenderId: '163516367513',
    projectId: 'guia-roteiro-vinho',
    storageBucket: 'guia-roteiro-vinho.firebasestorage.app',
    iosClientId: '163516367513-c7lud1p4bppbf10ro7bdqfgjc7o407fu.apps.googleusercontent.com',
    iosBundleId: 'br.com.fatec.guiaRoteiroVinho',
  );

}